spring:
  application:
    name: graphql-servers-java

---
spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always

logging:
  level:
    io.micrometer.core.instrument.logging.*: true
    com:
      netflix:
        graphql: DEBUG
        logging:
          level:
            web: DEBUG

